AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - vendor/**/*
Layout/IndentationStyle:
  Enabled: false
Layout/IndentationWidth:
  Width: 2
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Layout/LineLength:
  Max: 120
  Exclude:
    - spec/**/*
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - lib/app.rb
Style/IfUnlessModifier:
  Enabled: false
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/RegexpLiteral:
  Enabled: false
Style/StderrPuts:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/BlockComments:
  Exclude:
    - "spec/**/*"
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Layout/ClosingParenthesisIndentation:
  Enabled: false
Layout/MultilineMethodCallBraceLayout:
  Enabled: false
Layout/ArgumentAlignment:
  Enabled: false
Layout/FirstArgumentIndentation:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/ClassAndModuleChildren:
  Exclude:
    - "config.ru"
Layout/TrailingWhitespace:
  Exclude:
    - "spec/templator_spec.rb"
Layout/CaseIndentation:
  EnforcedStyle: end
Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line
Naming/MethodParameterName:
  Exclude:
    - "lib/app.rb"
