version: "3"
services:
  gateway:
    container_name: influx-pushover-gateway
    image: "influx-pushover-gateway:latest"
    hostname: "influx-pushover-gateway"
    restart: unless-stopped
    ports:
      - 8080:9292
    volumes:
      - ~/.ejson/${APP_EJSON_KEY}:/opt/ejson/keys/${APP_EJSON_KEY}
      - ../config:/srv/config
